export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const CALL_ASYNC_PRODUCT_DATA='CALL_ASYNC_PRODUCT_DATA';
export const GET_ASYNC_PRODUCT_DATA='GET_ASYNC_PRODUCT_DATA';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SET_SEARCH_PRODUCT='SET_SEARCH_PRODUCT';
export const PRODUCT_API='http://localhost:4000/product';